### ISSUE TITLE
编译源码报错

### ISSUE THREAD

**Issue by kissggj123** [topjohnwu/MagiskManager#110]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.android.support:recyclerview-v7:25.1.1.
     Required by:
         project :app
   > Could not find com.android.support:cardview-v7:25.1.1.
     Required by:
         project :app
   > Could not find com.android.support:design:25.1.1.
     Required by:
         project :app
   > Could not find com.android.support:support-v4:25.1.1.
     Required by:
         project :app
   > Could not find com.android.support:support-annotations:25.1.0.
     Required by:
         project :app > com.jakewharton:butterknife:8.5.1
         project :app > com.jakewharton:butterknife:8.5.1 > com.jakewharton:butterknife-annotations:8.5.1
   > Could not find com.android.support:support-compat:25.1.0.
     Required by:
         project :app > com.jakewharton:butterknife:8.5.1
   > Could not find com.android.support:recyclerview-v7:25.1.1.
     Required by:
         project :app > com.thoughtbot:expandablerecyclerview:1.4
   > Could not find com.android.support:support-v4:25.1.1.
     Required by:
         project :app > com.thoughtbot:expandablerecyclerview:1.4 > com.android.support:appcompat-v7:23.4.0
         project :app > com.thoughtbot:expandablerecyclerview:1.4 > com.android.support:appcompat-v7:23.4.0 > com.android.support:support-vector-drawable:23.4.0
   > Could not find com.android.support:support-v4:25.1.1.
     Required by:
         project :app > com.google.android.gms:play-services-safetynet:9.0.1 > com.google.android.gms:play-services-basement:9.0.1

**Comment by topjohnwu** [comment]
這個錯誤是你的系統找不到需要的library
請使用最新beta版android studio，或是手動下載最新的Google SDK跟Google Play Service SDK
