### ISSUE TITLE
Magisk Hide not working since v4.1

### ISSUE THREAD

**Issue by Filip013** [topjohnwu/MagiskManager#112]
I am unable to activate Magisk Hide since v4.1 update. Here is the log of what happens when I try with v4.2:
[2017-02-19-20-48-52_MagiskHide.zip](https://github.com/topjohnwu/MagiskManager/files/786160/2017-02-19-20-48-52_MagiskHide.zip)
And this happens with v4.0:
[2017-02-19-21-01-04_MagiskHide.zip](https://github.com/topjohnwu/MagiskManager/files/786161/2017-02-19-21-01-04_MagiskHide.zip)

Right now I’m happy with v4.0, but I’d appreciate it if you looked into this.

Here is my old thread for reference:
https://github.com/topjohnwu/Magisk/issues/44

Edit: Forgot to provide more info. I use Magisk v11.1. My phone is Xiaomi Redmi Note 3 Pro and I’m running stock MIUI 8.1 based on Marshmallow.

**Comment by topjohnwu** [comment]
Are you on newer v11.1 Magisk?
Magisk Manager calls a script to do the work, also does Magisk core scripts.
You can check by executing 
`sh /magisk/.core/magiskhide/enable(disable)`
The script is not that complicated, maybe check what's wrong with the scripts, or maybe it is just the magiskhide binary isn't supported (the real binary is stored in `/magisk/.core/magiskhide/magiskhide`)

**Comment by Filip013** [comment]
Thanks for replying John, you’ve helped me a lot!
So the problem is definitely with Magisk Manager. I am using the latest Magisk v11.1. When I open the manager, I am not prompted to update. And since I can activate Magisk Hide with Manager v4.0 (and the latest Magisk v11.1), I don’t think there’s anything wrong with the binary.
More importantly, I ran your script in Terminal with su and Magisk Hide got activated! Now I’ve made a Tasker profile to activate the script on boot and it works.
I don’t know why Magisk Manager is unable to activate the script by itself... Maybe it needs su, I don’t see it requesting su but Terminal needed su to start the script... I have no idea.

**Comment by barnir** [comment]
I have this issue, using Miui Dev versions for Kenzo... what i did was.. on Kernel Auditor i added the script to Init.D

**Comment by chhapil** [comment]
thanks for this work around! This works on MIUI 8 Global beta 7.3.x Mi5.
the only side effect is Magisk Manager loses the root detection, but app like greenify, BBS still detect root.
but blocked apps like Airwatch dont detect it.

**Comment by sambul13** [comment]
Fix to enable MagiskHide in Magisk v12.0 is given [here](http://c.mi.com/thread-186985-1-0.html). Please merge.

**Comment by topjohnwu** [comment]
These problem do not belong to Magisk Manager, please report in XDA thread or Magisk repo
