### ISSUE TITLE
changes can't be restore to default after removing system.prop

### ISSUE THREAD

**Issue by wuchjun** [topjohnwu/MagiskManager#113]
i can only do is making a default change in system.prop to restore to default build.prop.

**Comment by Didgeridoohan** [comment]
To clarify: I believe this report is about persist props that do not revert to the default build.prop value after the module changing it (with system.prop) has been removed.

This issue should rather be under the Magisk repository.

**Comment by wuchjun** [comment]
yeah, it's the persist prop cause this problem which i discussed on the xda too. it shuld move to the Magisk repository.

**Comment by topjohnwu** [comment]
These problem do not belong to Magisk Manager, please report in XDA thread or Magisk repo
