### ISSUE TITLE
Improve code beauty #1

### ISSUE THREAD

**Issue by tonymanou** [topjohnwu/MagiskManager#114]
I would like to share some thoughts with you, and help you to improve the beauty of your code.
If you agree I will split these ideas into into multiple issues.

### 1) Braces

I saw you were removing braces from all those single-statement ```if```/```else``` blocks lately.
In my humble opinion, you really should revert back to using braces. (Same goes for ```for``` or ```while``` loops.)

While removing the braces makes the code shorter and more compact, these braces do add structure to the code and getting rid of them may lead to confusion and/or programming error that could be avoided...
*Been there, done that*, we humans are not infallible: I already saw people forgetting to remove the ```ìf``` that had no braces after removing the single-statement with a keyboard shortcut, or other people mislead by a broken indentation (this is another problem) and overlooking an ```ìf``` that had no braces without realizing the next two statements were not in the same ```if``` block:
```
if (someBoolean)
    doSomething();
    doSomeOtherThing();
```

For an example of the impact this lack of braces can have, you can check out [this article about Apple's security breach known as the "goto fail" bug](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/) which could have been avoided if they were using braces on their ```if```/```else```s.

Same goes with one-line ```if (condition) statement;```. I do understand that these one-line statements executed conditionally are pretty handy, but if the statement is a ```throw new Exception();``` you might want to wrap it into an helper method called ```enforceRightParameter(parameter)``` for instance (and then use a beautiful conditional block with braces, without growing the code were the condition was used before being wrapped). Android is using this kind of construction internally, see https://github.com/android/platform_frameworks_base/blob/82834baa358f55acb542e17da828b2d497cf8332/services/core/java/com/android/server/pm/PermissionsState.java#L578

**Side note:** it also adds overhead to not use braces for single-statement blocks. If someone is adding a statement to the block (respectively removing from), he will have to add braces to it (respectively maybe remove them if there is only one statement left in the block): in this case the developer is modifying more than one line in the file from the Git perspective... but what you want is keeping your Git history clean, with all the changes free from parasitic modifications so you can easily spot the core changes!

This being said, it's your call. IMHO code length should not take over code safety.

**Comment by topjohnwu** [comment]
Thanks for the recommendation, I just personally don't like how it looks like 📦 
I'll change most of it back with braces, just for future maintenance as you pointed out.
