### ISSUE TITLE
#109 wasn't fixed altogether

### ISSUE THREAD

**Issue by DeicPro** [topjohnwu/MagiskManager#116]
#109 
![screenshot_2017-02-21-03-29-29-000_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12710770/23148661/64c178f8-f7e7-11e6-879c-d1154afd3fb8.png)
![screenshot_2017-02-21-03-29-36-682_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12710770/23148660/64c1100c-f7e7-11e6-8fa9-d2c85c711b74.png)
![screenshot_2017-02-21-03-28-51-654_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12710770/23148662/64c1a9c2-f7e7-11e6-9e28-5c9a3685a593.png)
![screenshot_2017-02-21-03-29-11-730_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12710770/23148663/64c1b46c-f7e7-11e6-97ae-27df8d1eee6d.png)

**Comment by linar10** [comment]
Error in the translation file line 91

**Comment by DeicPro** [comment]
```
<string name="repo_install_msg">¿ Quieres instalar %1$s ?</string>
```

```
<string name="repo_install_msg">Do you want to install %1$s ?</string>
```

Where does @linar10 is the bug?

**Comment by linar10** [comment]
I thought that it was you with an inverted question mark. Translated better to add the 'Download and Install'.
No special characters

**Comment by DeicPro** [comment]
`¿` is needed when make a question in Spanish, is not a special character.

And this is not the problem... the problem is that text is malformed or cut in buttons. @linar10
