### ISSUE TITLE
Poor contrast with dark theme

### ISSUE THREAD

**Issue by josephcsible** [topjohnwu/MagiskManager#119]
The currently active item has very poor contrast when the dark theme is enabled. See the word ”status” in the below screenshot.
![screenshot_20170221-170245](https://cloud.githubusercontent.com/assets/16061266/23187154/d449df1a-f857-11e6-94dd-99a5ad872850.png)

**Comment by tonymanou** [comment]
@topjohnwu I guess this is linked to your removal of dark theme's style items ```colorPrimary``` and ```colorPrimaryDark``` in commit https://github.com/topjohnwu/MagiskManager/commit/8eba05ed4a20b6c17e89875cfaa73bfc51835b74#diff-6f870d7e261f41dd3e52a2a129fa1fc5 (and also the removal of dark themed colors in commit https://github.com/topjohnwu/MagiskManager/commit/a3f0ef8e772f4a85a01c7efebb248b959c03edd6#diff-b90dd5bd8f8d84662b2f78ce4110a07a)

**Comment by terrorist96** [comment]
See also the buttons on the top right on the Log page.

**Comment by terrorist96** [comment]
@topjohnwu is this being fixed in the next version? Why close it before fixing it?
