### ISSUE TITLE
Weirdness with MagiskManager directory on internal storage

### ISSUE THREAD

**Issue by bziemek** [topjohnwu/MagiskManager#12]
I'm very excited to be able to report this today - it means my phone took the update from 1.2/v6 like a champ!

Summary: cannot locate files written to internal storage via. Windows PC.
Expected behavior: the list of files in Explorer should match what my phone sees.
Device: LG H901 / Android: 6.0 / Windows: 10

Detail: when trying to update phh's SuperUser in-app, the flashing step errored out (probably not a "bug," and probably not worth reporting) so I went to save a log just in case. Magisk Manager saves the log to `/storage/emulated/0/MagiskManager` successfully, and I can browse to it on my device without issue. Upon plugging my phone in to my PC, however, the directory listing of `Device > Internal Storage > MagiskManager` seems to be totally wrong, even after rebooting the phone.

Here's what things look like on my end:
![magisk_manager_2 0-directory_inconsistency-adb_ls](https://cloud.githubusercontent.com/assets/12708218/19086461/3cb339d2-8a3c-11e6-8467-ea48277ce798.png)
![magisk_manager_2 0-directory_inconsistency-explorer](https://cloud.githubusercontent.com/assets/12708218/19086464/3eb44ce4-8a3c-11e6-992b-9e9d7d019e2a.png)

Aaaand... it's gone. I just ran a `find / -name phh.zip 2>/dev/null` and nothing came up. Now Explorer miraculously shows the correct files. Additionally, when I tried to update phh's SuperUser again, a new phh.zip appeared in Windows Explorer in real-time, but `find / -name phh.zip 2>/dev/null` still turns up nothing at all, and new logs saved from Magisk Manager still do not appear in Windows Explorer right away.

![image](https://cloud.githubusercontent.com/assets/12708218/19086916/1f6f5a0c-8a3e-11e6-9650-ebd0c43ec57a.png)

So, I'm at a loss. I'll try to clean up this report a bit if I can make any sense of this behavior. Thanks for all your hard work!

(P.S. This has probably got a lot to do with the extensive use of shell commands to move files around. Frankly, it would be a really good idea to convert as much file handling code as possible to official APIs for future releases.)

**Comment by topjohnwu** [comment]
Thanks for the detailed report! However, I think it shall be some random issues. I didn't used that much shell to mess with files, most file processing placed in internal storage are done by Java code.
