### ISSUE TITLE
[Feature] User definable repos

### ISSUE THREAD

**Issue by geekywalrus** [topjohnwu/MagiskManager#120]
Having the ability to add different repositories seems like it would be beneficial in more than one way. It would allow

* Developers to have Alpha/Beta repositories for their modules, so users can test at their own discretion without having to leave the app
* If using Magisk for a systemless ROM (like Viper10), the ROM could have its own repository with all of its changes put into individual modules for easy ROM updates

**Comment by topjohnwu** [comment]
That is too much effort lol, I'll consider it in the future
