### ISSUE TITLE
Magisk Hide list - Barclaycard

### ISSUE THREAD

**Issue by adroidnote4** [topjohnwu/MagiskManager#124]
Hi,

Please add Barclaycard (com.barclays.bca) to the default Magisk Hide list similar to Android Pay.

Having Barclaycard in the default list will preventing it detecting root if user forgets to tick in Magisk hide list before opening the app.

Not sure what has changed with Barclaycard, but it seems that if root is detected by Barclaycard at least once then it is not possible to remove the message "Rooted devices unsupported...you'll need to restore its factory settings".
Removing all traces of root, magisk etc and returning to stock settings still does not remove the root detection, only after a factory reset or a new install seems to do the trick.

Thanks

**Comment by flotux2** [comment]
Hi,

I've tested today with the current Magisk version 13.3 and the hide function but the app always claims to run on a rooted device. For me also reinstallation of the app did not help.

Please add support for this app.

Thanks
Florian
