### ISSUE TITLE
Resets timeline after reboot

### ISSUE THREAD

**Issue by Vitak0** [topjohnwu/MagiskManager#129]
After rebooting sets GTM+0 greenwich. magisk 11.1

**Comment by Didgeridoohan** [comment]
What kind of grounds do you have that Magisk has anything to do with this? And if you do, where are the logs and details?

**Comment by Vitak0** [comment]
It started after installing magisk and stopped after unistallining.
I don't have logs.

**Comment by Didgeridoohan** [comment]
It's gonna be hard to pinpoint and troubleshoot if the only information you can provide basically is: "it doesn't work".

Two good links for when reporting bugs:
https://forum.xda-developers.com/wiki/Reporting_A_Problem_-_Android
https://forum.xda-developers.com/showthread.php?t=1726238

**Comment by topjohnwu** [comment]
Don't know what you're reporting lol
