### ISSUE TITLE
force closes after a few seconds after v7 update

### ISSUE THREAD

**Issue by yuukiw** [topjohnwu/MagiskManager#13]
device S6 edge
ROM CARHD 23.1

What i tried:
- reinstalling the manager
- flashing new SHH root zip
- rebooting

**Comment by yuukiw** [comment]
[Magilog.docx](https://github.com/topjohnwu/MagiskManager/files/509571/Magilog.docx)

**Comment by yuukiw** [comment]
after a reboot it happens again

**Comment by yuukiw** [comment]
http://pastebin.com/Sm5eQSNE

Log.

**Comment by topjohnwu** [comment]
I think this is fixed
