### ISSUE TITLE
magisk hide not reacting

### ISSUE THREAD

**Issue by Artim96** [topjohnwu/MagiskManager#131]
Since I switched to version 12 20170304 (also present in 20170308, Magisk Manager both times the one tried the same day) Magisk hide seems to be not reacting at all, not when running a SafetyNet test and not when the also blacklisted RootBeer sample is running.
Reinstalling it does not change anything. I was able to get the Magisk log and a logcat log when running SafetyNet check inside the manager, but at least the Magisk logs sadly show nothing not normal besides the fact that there is nothing about Magisk hide in it.
[magisk_error_20170308_204138.txt](https://github.com/topjohnwu/MagiskManager/files/828881/magisk_error_20170308_204138.txt)
[Magisk-hide.txt](https://github.com/topjohnwu/MagiskManager/files/828882/Magisk-hide.txt)

If there is any way I can help you further, just let me know.

Device: Note 4 international (N910F) with AOSP 7.1.1 based EmotionOS. Magisk v11.1 worked fine besides the fact that I had to disable busybox in order to no always loose root

**Comment by cutesniper22** [comment]
Hi, I also have the similar issue with it.
Magisk Hide able to function properly with my MIUIv8 device by executing magisk hide enable script manually. (https://github.com/topjohnwu/MagiskManager/issues/112)

But when come to Magisk V12, I tried to execute enable script via terminal emulator but no response and no result returned.
[https://drive.google.com/open?id=0B5yzVKyzaC3GT3RoY0ZpNFZqd2M](url)

**Comment by topjohnwu** [comment]
A lot has changed, it should not be an issue on Magisk Manager's side
