### ISSUE TITLE
Loosing root after some time

### ISSUE THREAD

**Issue by c727** [topjohnwu/MagiskManager#133]
I installed the manager app (_no Magisk_) to check the translation on my CM 12.1/ Android 5.1.1 device with CM-root. After some time the SU-binary gets removed or whatever so I have to reflash my Rom to get rooted again. - I did not Install Magisk!

Maybe it's related to the issues about loosing root at xda..

**Comment by topjohnwu** [comment]
These problem do not belong to Magisk Manager, please report in XDA thread or Magisk repo
