### ISSUE TITLE
[Feature] Report if Magisk Hide has started on boot or not.

### ISSUE THREAD

**Issue by Didgeridoohan** [topjohnwu/MagiskManager#137]
As stated in the release thread, under FAQ, sometimes Magisk Hide doesn't get to start the boot process on boot. This might lead to users believing Magisk Hide isn't working at all...

Would it be possible to check if the daemon has started after boot and notify the user if it hasn't (assuming Magisk Hide is enabled in Manager). The user can be instructed to re-enable Magisk Hide and possibly reboot.

As a side-note, but related to this, if Magisk Hide does not start on boot, some parts of it (since v11.5) might not function properly. More precisely, I've found that ro.build.tags might not get set properly if Magisk Hide doesn't start at boot. The command getprop in terminal will report the new value (release-keys) but apps looking for it will report the original value (test-keys). This root checker, among others, can be used to test: https://play.google.com/store/apps/details?id=com.jrummyapps.rootchecker
This has been tested on a Nexus 6 with Pure Nexus 7.1.1_26 and Franco Kernel, Magisk v11.6.

**Comment by sambul13** [comment]
Fix to enable MagiskHide in Magisk v12.0 is given [here](http://c.mi.com/thread-186985-1-0.html). Please merge.

**Comment by Didgeridoohan** [comment]
1 - Kind of unrelated to this feature request.
2 - It's a known issue (MIUI specific I believe), reported here: https://github.com/topjohnwu/Magisk/issues/167
