### ISSUE TITLE
rooted but no root permission not allowed pls help

### ISSUE THREAD

**Issue by crusher42** [topjohnwu/MagiskManager#138]
i been trying this 3 times but i get this
![screenshot_2017-03-29-18-36-16](https://cloud.githubusercontent.com/assets/24504038/24443910/35a3c6e4-14b0-11e7-9b06-b2e4fc5d81ac.png)

**Comment by Sheykhnur** [comment]
I also have same problem.

**Comment by topjohnwu** [comment]
These problem do not belong to Magisk Manager, please report in XDA thread or Magisk repo
