### ISSUE TITLE
Treat xposed module like magisk does.

### ISSUE THREAD

**Issue by blackwing182** [topjohnwu/MagiskManager#144]
Most of us have a device that does not have much modifications. And we simply use xposef to change statusbar etc etc to style our phone in to something diferent.

My request consist in to bud xposed tbe same way magisk does.

If magisk got tbe love to be patched to bypass safetynet checks. 

Xposed systemless need to be treates equaly and got the same love patch as magisk does.

Otherwise magisk is selfish and inmature.

Magisk does a good job. This is only my point and opinion.

**Comment by topjohnwu** [comment]
What are you talking about? I **DO NOT** have the ability to hide Xposed. It's not me blacklisting Xposed, Xposed works fundamentally different than general Magisk modules
