### ISSUE TITLE
Magisk Manager 2.0 crashes if there is no root installed, and locked-out if root is disabled

### ISSUE THREAD

**Issue by fsworld009** [topjohnwu/MagiskManager#15]
Maybe related to issue #13 

After I installed Magisk v7, Xposed Magisk version, and Magisk Manager 2.0, every time I open the manager app, it immediately crashes:

![screenshot_20161006-003502](https://cloud.githubusercontent.com/assets/7109839/19140710/5d57517e-8b5d-11e6-85a0-3e6f72be3168.png)

There is a workaround to go in to the app but the app won't work properly so I'll left that out for now.
Then I flashed phh's SuperUser Magisk version, after that I can get into the Manager app.

Now here is the case I just ran into:
If I disable phh's SuperUser in Manager's module management page then reboot, the Magisk Manager will crash again just like before it was installed

However, there is no way I can re-enable phh's SuperUser since the module management page won't load anything even if I use some workaround to get into the app:
![screenshot_20161006-003516](https://cloud.githubusercontent.com/assets/7109839/19140731/77fc8d96-8b5d-11e6-9fa0-6872f5781bc7.png)

So at this point the only option I have for now is to uninstall the whole Magisk.

My device is
Google Nexus 5
Android 6.0.1

**Comment by yuukiw** [comment]
same issue here with the exceotion that root otherwise works as intendet.

**Comment by topjohnwu** [comment]
Fixed in this https://github.com/topjohnwu/MagiskManager/commit/a7da6cf172e8df6227d39710f1e339c363eda53d
Thanks for reporting!

**Comment by yuukiw** [comment]
when will the new apk be out?

**Comment by bziemek** [comment]
@yuukiw If you are rooted and root is working, then you do indeed have a separate issue and should reopen #13 with any additional details you can provide, such as an `adb logcat` from the moments where the crash occurs. This issue relates to trying to run the app when there is actually no root installed.
