### ISSUE TITLE
[Bug] Root Not Detected After Resume

### ISSUE THREAD

**Issue by gudenau** [topjohnwu/MagiskManager#152]
Sometimes when MagiskManager is suspended and I resume it root is not properly detected. Killing it and reopening it solves this problem.

Magisk version: v12
MagiskManager version: 4.3.1
MagiskSU version: 8:MAGISKSU (topjohnwu)
ROM: Pure Nexus
Android version: 7.1.1
Android patch: March 5, 2027
ROM version: 7.1.1-20170317-OFFICIAL
Installed modules: Emoji One v1.11

**Comment by DeicPro** [comment]
I can confirm this

**Comment by DeicPro** [comment]
That is another issue, open a new Issue.

For curiosity only. Do you enable Magisk Hide from terminal or added to the
`enable` file `su -c`?

**Comment by sou7611** [comment]
Using MagiskSU (not SuperSU), and MagiskHide is enabled from within Magisk Manager
