### ISSUE TITLE
Magisk busybox conflicts with existing busybox installation - Breaks Magisk Hide

### ISSUE THREAD

**Issue by Didgeridoohan** [topjohnwu/MagiskManager#153]
Several users have reported issues with Magisk Hide not working on their devices with the ROM Pure Nexus installed. So, I did some testing on my Nexus 6 and [Pure Nexus 7.1.2_r6](https://forum.xda-developers.com/nexus-6/development/rom-pure-nexus-project-t3148214).

By just enabling Magisk Hide, root can be hidden and SafetyNet passes. Here is a Magisk log after enabling Magisk Hide and restarting, after a SafetyNet check (systemless hosts is also enabled at this point, but had no impact on Magisk Hide during my tests):
[magisk_error_20170424_182329.txt](https://github.com/topjohnwu/MagiskManager/files/952471/magisk_error_20170424_182329.txt)

After enabling Magisk busybox and rebooting the log shows that Magisk Hide does not start:
[magisk_error_20170424_182518.txt](https://github.com/topjohnwu/MagiskManager/files/952474/magisk_error_20170424_182518.txt)

Toggling Magisk Hide off and on again seems to make it start, but it does not unmount. Here is a log after toggling Hide and doing a SafetyNet check:
[magisk_error_20170424_182537.txt](https://github.com/topjohnwu/MagiskManager/files/952477/magisk_error_20170424_182537.txt)

Toggling Magisk Hide off and on by terminal command gives the following output:
```
shamu:/ $ su
shamu:/ # sh /magisk/.core/magiskhide/disable
1|shamu:/ # sh /magisk/.core/magiskhide/enable
MagiskHide: Moving and re-linking /sbin binaries
MagiskHide: Removing dangerous read-only system props
MagiskHide: resetprop by nkk71 & topjohnwu
Initializing...
Modify data structure: 'ro.boot.flash.locked'='1'
Existing property: 'ro.boot.flash.locked'='0'
Recheck property: 'ro.boot.flash.locked'='1'
Done!
MagiskHide: Killing com.google.android.gms.unstable
/dev/busybox/ps: invalid option -- o
BusyBox v1.22.1 bionic (2017-04-23 19:26 -0400) multi-call binary.

Usage: ps

Show list of processes

        -Z      Show selinux context
        w       Wide output
        l       Long output
        T       Show threads

MagiskHide: Starting MagiskHide daemon
shamu:/ #
```

Suggestion: Disable Magisk built-in busybox if an existing busybox installation is found.

Edit:
This is with Magisk v12 and Magisk Manager 4.3.1.

**Comment by boldi21** [comment]
I have same problem!

**Comment by boldi21** [comment]
I did it, but this problem is remaining!

**Comment by topjohnwu** [comment]
Well, maybe wait for Magisk v13 since no more busybox is involved

**Comment by Didgeridoohan** [comment]
In light of how the next release of Magisk is progressing, this issue seems to be a non-issue, so I'm closing the issue. :)

**Comment by boldi21** [comment]
Dear topjohnwu!

One note! I dont know what exactly changed from Magisk 11.6 to 12, but when I flashing older v11.6 then all banking program works for me! Does You help me find the problem, "bug" with v12?

**Comment by Didgeridoohan** [comment]
@boldi21
A slightly misplaced request for help... A closed GitHub issue about something completely different.

Anyway...

Magisk v11.6 changed a couple of build.prop values that were removed in v12. To many possibilities for issues. You can change them yourself with a Magisk module or a boot script. More info on that in the Magisk forum on XDA.

The props are:
ro.build.tags (value should be release-keys)
ro.build.type (value should be user)

The most likely culprit is tags...
