### ISSUE TITLE
Android 4.4 Parsing Error

### ISSUE THREAD

**Issue by JokerGermany** [topjohnwu/MagiskManager#16]
When I try to Install the MagiskManager i get a Parsing Error.

**Comment by Lrs121** [comment]
Magisk is meant only for newer versions of Android. 5.x and greater I believe

**Comment by topjohnwu** [comment]
Magisk is meant for 5.0+

**Comment by TheComputerGuy96** [comment]
Why you can't make it work on KitKat?
