### ISSUE TITLE
[Feature request] Hide Magisk's features that are incompatible

### ISSUE THREAD

**Issue by TheComputerGuy96** [topjohnwu/MagiskManager#166]
@topjohnwu That would be a nice feature

Example: Most Lollipop ROMs don't feature setns support for the mount namespace and thus, they're incompatible with Magisk Hide (so Magisk Hide shouldn't be listed)

**Comment by topjohnwu** [comment]
This would be difficult in the MagiskManager side. The only way I can think if is to inquire the magisk main binary whether setns is supported. I'll put this on my TODO list, but the priority should be very low.

**Comment by Didgeridoohan** [comment]
That's interesting. I read up a little on setns, but couldn't find what I'm looking for.

Is there an easy way to check if setns is supported?

**Comment by TheComputerGuy96** [comment]
@Didgeridoohan setns support for the mount namespace is required to pass Android Marshmallow+ CTS test (for Storage permission to work dynamically)
