### ISSUE TITLE
[Issue] Some banking apps detect the Magisk Manager app

### ISSUE THREAD

**Issue by TheComputerGuy96** [topjohnwu/MagiskManager#176]
@topjohnwu @lalitjoshi06 from XDA told us the issue in [this post](https://forum.xda-developers.com/showpost.php?p=72503900&postcount=14107):
> **Solution for all banking apps which detects root or other protection.**
> I am sharing this here for the information to developer. 
> I am using this on unofficial magisk snapshoot version 170531. (So Try it with stable version can solve issue > for most peoples)
> 1. Safety net must be passed.
> I am using leeco X526 with us X522 Rom and magisk version 170531 build.
> just install app and tick in magisk hide and reboot device.
> now open your banking app it detect root, no worry.
> just uninstall magisk manager app and open your bank app it will work.
> **@ Developers now the point is these banking apps is detecting this app (magisk manager) and not working.**
> so when need to use banking app just uninstall the app and after again install this and all is ok, root works.
> I checked this on Spushtan and UOB apps and its working.
> if this app can be able to hide itself then all banking apps will work without any issue.
> developer must to see in this matter. (Banking apps just detecting this app and force closing nothing else)
> Thanks.

**Comment by DeicPro** [comment]
I'm thinking... If you install Magisk Manager systemlessly​, so a module que bind mount the app in system.. that must hide Magisk Manager when Magisk Hide does its work

**Comment by DeicPro** [comment]
I tried and did not work (I uninstall Magisk Manager user app before obviously).. Too without Magisk Manager, S-pushTAN force close, so could be Magisk v12 is detected or something.

**Comment by lalitjoshi06** [comment]
First hide spushtan app in magisk hide then reboot and then uninstall magisk app. Spushtan works.
Not sure for v12 as I am on 31st may build unofficial.

**Comment by DeicPro** [comment]
obviously I hide the app haha...

**Comment by lalitjoshi06** [comment]
and one more thing just confirm before doing anything.
without any root module "Spushtan is working on your rom" , if without any root spushtan is working than this method will work 100%.
Thanks (Try and report)

**Comment by DeicPro** [comment]
Magisk v13 doesn't work good... Magisk Hide fails to hide root I tried all..

**Comment by zanglang** [comment]
Interesting freezing Magisk Manager with Titanium Backup works for unblocking UOB. I'm guessing that it effectively removes Magisk from the installed apps list API.
