### ISSUE TITLE
The Manager status screen looks garbled

### ISSUE THREAD

**Issue by ADeadTrousers** [topjohnwu/MagiskManager#181]
![tmp_8973-screenshot_20170604-17181972490408](https://cloud.githubusercontent.com/assets/28513067/26763096/10be92e2-494d-11e7-9195-09647db245e4.png)
I'm not sure if it is supposed to look like this, but currently its not very intuitiv.
I'm using the unofficial build by stangri. Everything else ist working ad expected.

**Comment by ADeadTrousers** [comment]
Oh, sorry I forgot:
It's a Galaxy S5 Mini (G800F) running LineageOS 14.1
It looks like the status screen and the install screen got mashed together.

**Comment by TICG** [comment]
Yes, that's the new design buddy, I built the newest commits for Magisk Manager, it looks the same. 

_Sent from my Samsung SM-G925P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ADeadTrousers** [comment]
Thanks for the clarification.
I was hoping that it's a glitch of some kind, because in my opinion the old style with two different screens was much better. But if that's what they decided it should look like than it should be.
