### ISSUE TITLE
Help! Phone Won't Boot!

### ISSUE THREAD

**Issue by RarePika** [topjohnwu/MagiskManager#189]
So, I tried to install Magisk on Android 4.4. I used TWRP to intall it. But it gave me an error saying that it wasn't compatible. So I brush it off and try to reboot, only to find that my phone wont boot and is stuck on a screen saying T-Mobile. Please help!

P.S. You should make the "Only for 5.0+" Thing more obvious on the xda page.

**Comment by DeicPro** [comment]
you must report this in https://github.com/topjohnwu/Magisk/issues, but you have got reason, the `updater-binary` part that checks for Android SDK version must to be before than anything...

**Comment by DeicPro** [comment]
I did a pull request that may fix this

**Comment by RarePika** [comment]
Can you tell me how to do that, or reference me somewhere. I'm new to TWRP.

**Comment by DeicPro** [comment]
Download a ROM for you device and in TWRP press "Install" and go to the zip of the ROM... And the next time you try to flash something from TWRP, do a backup from it to can restore if something goes wrong

**Comment by RarePika** [comment]
OK Thanks
