### ISSUE TITLE
Magisk su v.13 issue with samsung note 3

### ISSUE THREAD

**Issue by atarek1** [topjohnwu/MagiskManager#192]
I have samsung note 3 n9005 
Rom: S7E Port 6.0.1 by NXTeam (darklord reborn).
Kernel: Phantom v.1.2k (6h0st).
Recovery: TWRP materialized V:2.8.7.0.

i was using magisk su v.12 and magisk manager v:3.4.4 before google update and every thing was working flawlessly.
I decided to try beta test so i followed these steps:
* uninstalled magisk manager v:3.4
*Boot to recovery and run "Magisk-uninstaller-20170320.zip"
*run Magisk-v13.0(a90e8b6).zip then reboot but manager wasn't installed after boot up so i installed it manually from zip file but it didn't detect magisk installed i try to return manager 3.4 and v.12 then try to run "Magisk-v13.0(a90e8b6).zip" as a module installation and update manager but also no root detected.
So i booted to recovery flashed "Magisk-uninstaller-20170320.zip" then my Kernel then
*run Magisk-v13.0(96f8efc).zip but i got attatched error and recovery log.
*also i can't flash any other version again. 
so I returned to my stable state with version 12 and manager 3.4 and started testing again i flashed "Magisk-uninstaller-20170608" then flashed "a90e8b6" and rebooted i found old magisk manager so i uninstalled it and extracted manager in "96f8efc" and installed it. attatched screenshots and adb log.
Any advice. regarding this issue or regarding "96f8efc" flashing issue in TWRP mentioned in previos post.
Also as my knowledge magisk v13 flashable should install magisk manager why this not happen with me.
i could support any kind of info or logcat required and i'm ready to test any scenario.
 
![screenshot_20170616-131522](https://user-images.githubusercontent.com/29482903/27226253-5e792f24-529e-11e7-9f63-5c933a946694.jpg)
![screenshot_20170616-131538](https://user-images.githubusercontent.com/29482903/27226254-5e7b194c-529e-11e7-91d1-77a431faa595.jpg)
[magisksu_log.txt](https://github.com/topjohnwu/MagiskManager/files/1080716/magisksu_log.txt)
[96f8efc_recovery.txt](https://github.com/topjohnwu/MagiskManager/files/1080721/96f8efc_recovery.txt)
[a90e8b6_recovery.txt](https://github.com/topjohnwu/MagiskManager/files/1080722/a90e8b6_recovery.txt)

**Comment by Didgeridoohan** [comment]
This is not an issue with the Manager. Should be moved to the [Magisk repo](https://github.com/topjohnwu/Magisk/issues).

**Comment by tanago** [comment]
Did you fix it?

**Comment by atarek1** [comment]
yup latest beta "c4377ed" is working flawlessly except manager still didn't installed automatically.
