### ISSUE TITLE
Magisk Manager refuses to install modules from repo (This ZIP is not a Magisk Module!)

### ISSUE THREAD

**Issue by stangri** [topjohnwu/MagiskManager#20]
Here's the discussion: http://forum.xda-developers.com/apps/magisk/guide-magisk-refuses-to-install-modules-t3484554

I've had magisk installed since version 6, I've published some magisk modules already and never had a problem until today.

After a full clean reinstall of Nougat NBD90Z (with wipe) on my Nexus 6 and then flashing Magisk, phh's superuser for magisk, installing phh's superuser apk from play store and magisk manager apk I stumbled upon a previously reported (without details) bug where magisk manager would refuse to install modules from repo claiming they are not magisk modules.

I've struggled trying everything I could including the full wipe (more details here: http://forum.xda-developers.com/apps/magisk/module-app-systemizer-t3477512/69230448#69230448) and bounced some ideas off @pnwsr6 who's had the similar problem on Nexus 6 device.

Neither restoring boot image, nor dirty-flashing the whole system image, nor full reflash with wipe worked.

I've achieved a partially working Magisk Manager (manual installs of ZIP files work, but installs from repo still fail) and here's the list of steps which lead to me having semi-working magisk manager again:
1. I flashed ZIP files of some modules in twrp (I'm attaching App Systemizer and Nexus 6 LED Enabler which I flashed) 
2. After the phone booted up I saw the modules active and working
3. Within Magisk Manager I then added the ZIP file of the phh's superuser module from that thread 
4. Now at least manual installation of modules within Magisk Manager are working fine. 

@topjohnwu -- I've enabled verbose logging and extra logging for bash commands, but I'm still not seeing anything in the log on top of the regular output.

**Comment by Yeradon** [comment]
Works fine for me with the new version.

**Comment by GhostlyCrowd** [comment]
Same issue as OP

**Comment by topjohnwu** [comment]
I might need to rewrite the whole zip processing part, but will take some time to finish.

**Comment by stangri** [comment]
@topjohnwu will it affect the existing modules? will they need to refresh their update-binary?

**Comment by hugoserrana** [comment]
Same here. But after error I Checked the modules path and the zip is not there.
i think that is a download or file writing error.
Maybe in ModuleFragment.java, you shouldn' t check on onActivityResult if data is FETCH_ZIP_CODE for requestcode type data?

**Comment by topjohnwu** [comment]
Please check from 2a8477cbda2d67d6bc8749e1b8d890366614b3e5 to 4daea7d7e666f3cdd5cfaa98df66a869a0c5a440
I rewritten all zip processing with Java, also added zip signing to the app. I think this will fix all issues :)

**Comment by hugoserrana** [comment]
@topjohnwu I clonned repo and build the app for test and now is its working!
Thanks!

**Comment by stangri** [comment]
@topjohnwu while you're on the roll, could you please consider processing the ZIP files downloaded from github or otherwise having a nested folder matching the name of the ZIP file?

**Comment by topjohnwu** [comment]
@stangri, only zips downloaded from Github is processed :)

**Comment by DrMahmoodMirza** [comment]
On Samsung Note 10.1 SM-P600 with android 5.1.1 UESDPL1, rooted systemlessay with Supersu 2.79sr4, installed Magisk Manager from playstore, the official Magisk v12 installed failed again and again. Even after replacing the initially installed Magisk Manager with latest one  from the official repository, even then the official Magisk v12 could not be installed. I could not wiki how to manually install latest Magisk with the M.Manager, I don't have custom recovery. Kindly help me.
