### ISSUE TITLE
Crash when navigating to Superuser sub-menu (c4377ed)

### ISSUE THREAD

**Issue by andyrichardson** [topjohnwu/MagiskManager#201]
I've posted this on the official XDA thread although I think it is better to be noted here.

On the latest build (c4377ed) Magisk Manager is crashing when navigating to the Superuser menu entry. 

Despite this, the toast prompt for root permission requests and their respective grants are working fine. This issue doesn't seem to effect functionality, more just the management of root access.

The build in Magisk log (attached) doesn't seem to provide much information, however the following logcat output may be of help: 

```
07-03 12:39:20.762 13030 13030 E AndroidRuntime: Process: com.topjohnwu.magisk, PID: 13030
07-03 12:39:20.762 13030 13030 E AndroidRuntime:        at com.topjohnwu.magisk.b.b.a(Unknown Source)
07-03 12:39:20.762 13030 13030 E AndroidRuntime:        at com.topjohnwu.magisk.b.b.a(Unknown Source)
07-03 12:39:20.762 13030 13030 E AndroidRuntime:        at com.topjohnwu.magisk.SuperuserFragment.a(Unknown Source)
07-03 12:39:20.762 13030 13030 E AndroidRuntime:        at com.topjohnwu.magisk.MainActivity.a(Unknown Source)
07-03 12:39:20.762 13030 13030 E AndroidRuntime:        at com.topjohnwu.magisk.MainActivity.d(Unknown Source)
07-03 12:39:20.762 13030 13030 E AndroidRuntime:        at com.topjohnwu.magisk.MainActivity.b(Unknown Source)
07-03 12:39:20.762 13030 13030 E AndroidRuntime:        at com.topjohnwu.magisk.r.run(Unknown Source)
07-03 12:39:20.766  1538  5405 W ActivityManager:   Force finishing activity com.topjohnwu.magisk/.MainActivity
```

**Logs:**
[magisk-logcat.txt](https://github.com/topjohnwu/MagiskManager/files/1119395/magisk-logcat.txt)
[magisk_error_20170703_130311.txt](https://github.com/topjohnwu/MagiskManager/files/1119396/magisk_error_20170703_130311.txt)

**Comment by abelyi100** [comment]
You can use the uninstaller.zip to uninstall Magisk in TWRP, boot up, then boot to TWRP, flash Magisk again and see if the problem still exists.

I've once having similar problems in some build in v13, that Magisk Manager crashed every time when navigating to the log menu, and reinstall the whole Magisk just solve the problem.(Even clearing the data of the manager in settings doesn't work!)

**Comment by andyrichardson** [comment]
Thanks for the suggestion @abelyi100, after removing Magisk, rebooting, and then installing Magisk again, the issue has gone. 

I suspect the cause of the bug was due to not rebooting between uninstalling Magisk V12 and installing Magisk V13.
