### ISSUE TITLE
The design gets messy when shown in different languages

### ISSUE THREAD

**Issue by Arwany** [topjohnwu/MagiskManager#203]
Not that it bothers me, but it would be always nice to have it nice- looking...

Like this:

![screenshot_20170709-232144](https://user-images.githubusercontent.com/559250/27997659-a7b9572e-64fd-11e7-862b-753823a820b6.png)

**Comment by Arwany** [comment]
I see it has been fixed. Thanks guys!

![screenshot_20170715-165240](https://user-images.githubusercontent.com/559250/28240247-2cfb688a-697e-11e7-8663-b789949e76d3.png)

**Comment by guest4711** [comment]
So please close the issue...
