### ISSUE TITLE
The response is invalid

### ISSUE THREAD

**Issue by Raymond360** [topjohnwu/MagiskManager#204]
When I check SafetyNet it tells me the response is invalid and i had installed v13 and I searched all over the internet and didn't find anything

**Comment by multi-rom-user** [comment]
Do you use opengapps, dynamicgapps, microG?

**Comment by Raymond360** [comment]
I had installed opengapps (stock)

**Comment by multi-rom-user** [comment]
Have you tried uninstalling magisk fully and reinstall it?

**Comment by Raymond360** [comment]
Yes and it didn't work and I also tried the safetynet  bypass fix and it also didn't work

**Comment by multi-rom-user** [comment]
Are you able to edit your post and upload a screenshot of the effort?

**Comment by Raymond360** [comment]
I don't have an upload option

**Comment by DeicPro** [comment]
Raymon, I think I replied you in my thread. Follow my instructions. Just in case: Magisk v12 + v2 Beta 4, and the logs and screenshot of RootBeer

**Comment by Fischy667** [comment]
I have the same problem. Where can I can find the instructions to fix this.

Thanks.

**Comment by DeicPro** [comment]
Go to terminal:
`su`
`kill -9 $(busybox ps | grep "com.google.android.gms" | busybox awk '{ print $1 }')`

**Comment by TheComputerGuy96** [comment]
@Raymond360 What's your device and ROM?

_Sent from my Samsung GT-S7580 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Fischy667** [comment]
Samsung Galaxy S7, crdroid 7.1.2

And command didn't work (No such process) 

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Fischy667** [comment]
The command doesn't work: No such process. 

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DeicPro** [comment]
@Fischy667 that's the problem then, Google Play Services are not started when request the SafetyNet test... Update it and clear data..

Anyway try this and show the output, just in case:
```
busybox ps | grep "com.google.android.gms"
```

**Comment by Fischy667** [comment]
@DeicPro 
busybox ps | grep "com.google.android.gms"
21394 u0_a211    0:00 grep com.google.android.gms



_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Yourboymusti** [comment]
I've got a note 4 (N910F) Resurrection Remix 7.1.2. I've also got GAPPs installed.

For the first code: su -c kill -9 $(busybox ps | grep "com.google.android.gms" | busybox awk '{ print $1 }')
I get sh: su: not found

2nd code: busybox ps | grep "com.google.android.gms"

I got 335 root, 3040 S grep com.google.android.gms

I've cleared cache and data from Play Services.

**Comment by soarqin** [comment]
same here, and I noticed that the app "safetynet attest" cannot be started(or said crash immediately) if in hide list
I use OnePlus3 with OxygenOS 4.1.6

**Comment by DeicPro** [comment]
@soarqin Why is that app in hide list? It's using SafetyNet process, which is hided by default. Hiding that app does nothing.

**Comment by soarqin** [comment]
@DeicPro If I do not add this apo to hide list, it starts but cannot pass safetynet.
While it was in 12.0 and 13.0beta, this app can only pass safetynet check if added to hided list

**Comment by DeicPro** [comment]
I can bypass SafetyNet without hide it... as I said you, the process of the app itself is not checking for SafetyNet, the app use the SafetyNet API and run the Google Play Services SafetyNet process which is hided by default and is the only needed to bypass SafetyNet in all apps which using this security detection.

**Comment by soarqin** [comment]
@DeicPro but add it to hide list shoud not get any defect like mine. Also I get the same message(The response is invalid) in Magisk Manager whicle checking SafetyNet as reporter, I do think  the two issues are caused by the same reason.

**Comment by DeicPro** [comment]
The response is invalid is a Google Play Services issue.. I got that one time and killing the process (or reboot) did it the job.. but in your case, must try to update to the last version (use apkmirror) and clear data of Google Play Services

**Comment by soarqin** [comment]
@DeicPro I have latest google play service installed, also I tried to make a clean install of OxygenOS, nothing made help
