### ISSUE TITLE
Update checker bug

### ISSUE THREAD

**Issue by NinjaBoyLao** [topjohnwu/MagiskManager#205]
When I open version 5.0.4 of the manager app, it acts like it can check for updates, but spins forever and doesn't get anywhere. My internet connection is fine, but i tried it on two other networks as well, to the same effect. device is Moto X Pure with stock ROM and TWRP recovery image. I'm trying to figure out how to attach logs right now.

**Comment by NinjaBoyLao** [comment]
Aha. So i accidentally discovered, when trying to lazily swipe down from the top and check my notifications, that the manager has a "refresh" feature similar to chrome. The issue i mentioned resolves itself upon doing this. It will reappear when i close manager and reopen it however.

**Comment by terrorist96** [comment]
I can reproduce this. Opening the app for the first time will lead it to spin forever. Swiping down to do a refresh will quickly determine whether or not there is an update.

**Comment by NinjaBoyLao** [comment]
Issue is present in 5.0.5 as well.

**Comment by terrorist96** [comment]
This seems to have been fixed in 5.0.6.

**Comment by NinjaBoyLao** [comment]
sort of. closing the app and reopening will still cause this issue for me. if the app is already running and i just go back to it from the "recent apps" view its okay though

**Comment by terrorist96** [comment]
Killing the app doesn't reproduce it for me anymore. I just tried and the loading animation went away after a few seconds.

**Comment by NinjaBoyLao** [comment]
huh, i guess i'm just impatient. i can swipe down and get it to verify faster than waiting. oh well lol
