### ISSUE TITLE
Super user button crash

### ISSUE THREAD

**Issue by wingedonezero** [topjohnwu/MagiskManager#207]
When ever i hit the menu button on the left and click super user the app crashes and ssys stopped responding. Happens everytime im on lineage os and have a lg g4. But it also does it on my stock lg g2 as well.

**Comment by Aaron1011** [comment]
@wingedonezero: Can you run an `adb logcat` before clicking 'Super User', and upload the output? I had the same issue, which was caused by a corrupted/improperly migrated SQlite database used by MagiskManager (`su.db`).

**Comment by JERW86** [comment]
@wingedonezero look [here](https://forum.xda-developers.com/showpost.php?p=72793628&postcount=1852).

**Comment by wingedonezero** [comment]
@JERW86 that fixed it ill have to remember that next time theres a update thanks for the help.
