### ISSUE TITLE
App crashes if SafetyNet check is tapped during already ongoing check

### ISSUE THREAD

**Issue by kykc** [topjohnwu/MagiskManager#208]
Just a minor thing that I've noticed:

1. Tap SafetyNet Check
2. Quickly while app waits for response tap the check another time
3. App crashes

Reproduced on ``Nexus 5X`` and ``Xiaomi Redmi Pro`` using latest ``Magisk 13.1`` and ``MagiskManager v5.0.4``

**Comment by Didgeridoohan** [comment]
Confirmed on a OnePlus 3T, OOS 4.1.6, Magisk 13.1,  Manager v5.0.4. Logcat attached.
[SafetyNet_crash_logcat.txt](https://github.com/topjohnwu/MagiskManager/files/1140081/SafetyNet_crash_logcat.txt)
