### ISSUE TITLE
Installing v8 over v7 results in boot-to-recovery

### ISSUE THREAD

**Issue by jimbo1qaz** [topjohnwu/MagiskManager#21]
Amazon/Blu R1 HD, Android 6.0.1, Magisk Manager.

I previously installed Magisk v7 using SuperSU. However, when I try to update to v8, rebooting causes the phone to enter the Blu logo, reboot, and enter TWRP recovery instead.

I worked around the bug by restoring the stock boot image, then installing v8 into it.

Can this bug be fixed?

**Comment by aviraxp** [comment]
As mentioned in the V8 changelog, if you use systemless supersu, you should restore stock boot.img, then flash systemless supersu, and flash magisk.

> 
> In the previous release (v7), I decided to automatically convert SuperSU into a Magisk module while installing Magisk. In this release (v8), I make Magisk 100% compatible with SuperSU out of box, not needed to modify how SuperSU work in anyway. For v8 and future releases, Magisk will detect SuperSU patched boot image, and only add the required additional patches to the boot image.
> Also, I created further integration for Magisk and SuperSU: Magisk will create a script placed in /data/custom_ramdisk_patch.sh when SuperSU detected. What this means is that the next time you upgrade SuperSU by flashing SuperSU zip in custom recovery, Magisk will automatically be injected. You can also apply OTA updates with FlashFire, and enable SuperSU injection, which will also inject Magisk on-the-go!
> 
> For users that was using v7 with SuperSU along with the Helper Module, please manually restore your boot image (should be stored in /data/stock_boot.img), and flash the latest SuperSU, then flash Magisk-v8.

**Comment by jimbo1qaz** [comment]
Whoops...

Magisk Manager doesn't show full changelogs, I think...

**Comment by topjohnwu** [comment]
Not a Manager bug I think...
