### ISSUE TITLE
Magisk bug

### ISSUE THREAD

**Issue by araminimichael** [topjohnwu/MagiskManager#210]
Hello I am not développer and juste want to report this bug. (And I you want detail, explain to me to get it.)  
I have yotaphone 2 on android 6.0 (in Android 5 the bug for magisk v12 is same)

I flash magisk and install magisk manager. On android 5 and magisk v12. 

Magisk is installed and detect but root (with magisk not work, with SuperSu 2.82 work but loose root on reboot and with king orion work and reboot resist. 

With v13  magisk and magisk manager the flash work but on magisk manager see not installed but magiskSu (work and magisk manager see correctly rooted. And resist reboot. 

I you have any idea to get both magisk v13 with root or magisk v12 with root resist ? 

Thankx for your job. Is very useful app and I get dolby atmos work only with your app and is the only way to get work on yotaphone 2

**Comment by topjohnwu** [comment]
This issue does not belong to Magisk Manager
