### ISSUE TITLE
Correct line ending (UNIX LF) detection during module installation

### ISSUE THREAD

**Issue by rockypra** [topjohnwu/MagiskManager#224]
I'm new to Magisk world and I found a bug that was a bit silly but it might causes boot loop on some cases. 
It happened when I'm trying to create a module on Windows and forgot to convert the line ending to UNIX. During installation it looks OK but after finishing installation and after asked me to reboot, the module information is not complete and looks like it wasn't readable. After reboot, Magisk Manager shows multiple module with no name and informations that cannot be disabled or removed. After I check /magisk directory. I found that the magisk.img is corrupted and becomes unusable because it creates some folder with random unreadable characters surrounding the id of the module that can't be removed. Luckily it doesn't make my device trapped into boot loop and the only way to fix it is to fully reinstall Magisk. I think it was caused by wrong line ending used on config.sh and module.prop file. There should be a way to prevent this from happening within Magisk Manager.

**Comment by topjohnwu** [comment]
I think I had stated pretty clearly in magisk-module-template's [README.md](https://github.com/topjohnwu/magisk-module-template/blob/master/README.md).....
