### ISSUE TITLE
[Request]希望 Magisk hide 自動加入台灣行動支付

### ISSUE THREAD

**Issue by david082321** [topjohnwu/MagiskManager#226]
既然能自動加入android pay，要不要把行動支付(會檢測root權限)的應用程式都加進來？

底下附包名(package name)：
com.easycard.wallet
com.easycard.wallet.nonfc
tw.com.twmp.twhcewallet
com.esunbank.ESUNWALLET

**Comment by abelyi100** [comment]
這樣他要加的app也太多了啦XD，
從三大電信的nfc悠遊卡到各個銀行app他都要加一遍
而且又不只有台灣，還有國外的app，要這樣搞根本一輩子也加不完，

我們自己加進去就好了不用連這點小事都要麻煩他幫大家做好

**Comment by abelyi100** [comment]
而且如果這樣做，說不定會再提高Magisk的曝光度，要是哪一天這些app像作者說的，直接幹出去偵測Magisk Manager的存在這種事情就麻煩了
