### ISSUE TITLE
Magisk Manager can't update itself

### ISSUE THREAD

**Issue by krokofant** [topjohnwu/MagiskManager#227]
Currently on latest stable manager from XDA labs repo. Repeatedly get notifications about a new manager update.

Magisk v13.1 installed.
Manager 5.0.5

I usually update magisk as well as the manager when there is a companion release but this notification seems strange. I seem to have the latest manager but not magisk yet it yells about a new manager version.

![](http://i.imgur.com/6RLzBPC.jpg)

![](http://i.imgur.com/f0b3GHi.jpg)

**Comment by krokofant** [comment]
Clicking the update notification seems to do nothing.

**Comment by shinji257** [comment]
Current versions are Magisk 13.3 and Magisk Manager 5.1.0 so the app isn't wrong.  Kinda strange it doesn't allow you to download the newest version of the manager.

**Comment by krokofant** [comment]
@shinji257 I see. But why isn't there a manager update on XDA Labs?

I get this error in the logcat while trying to download the update via the notification.

```
07-19 01:09:21.994 W/DownloadManager(5224): Path appears to be invalid: /storage/emulated/0/MagiskManager/MagiskManager-v5.1.0.apk
```
The folder does exist.

**Comment by coderobe** [comment]
Click on Download & Install...

**Comment by krokofant** [comment]
> Click on Download & Install - Magisk 13.3 will update the Manager
Magisk 13.1 is installed and as previously stated the update notification does not work - which this issue is about.

**Comment by coderobe** [comment]
I'm not talking about the notification. Click the button in MagiskManager to flash 13.3 - no notifications involved.

**Comment by krokofant** [comment]
@coderobe I see. It seems to produce a similar error.

```
07-20 01:47:26.406 W/DownloadManager(5224): Path appears to be invalid: /storage/emulated/0/MagiskManager/Magisk-v13.3.zip
```
A friend of mine has the same problem.

Both are on OxygenOS stable and beta build respectively.

**Comment by coderobe** [comment]
That's interesting. Does /storage/emulated/0 map to your internal storage correctly and does the MagiskManager dir exist?

**Comment by krokofant** [comment]
@coderobe Yes

**Comment by topjohnwu** [comment]
I think I had fixed all issues regarding updating APK through notifications.
The version you are using might be outdated (the OTA feature used to be buggy)
