### ISSUE TITLE
Unable to disable Magisk Hide

### ISSUE THREAD

**Issue by fsworld009** [topjohnwu/MagiskManager#23]
Checked "Enable Magisk Hide" then reboot to take effect.

After doing some tests I want to disable Magisk hide but found that I cannot disable it anymore.
Everytime I reboot, the checkbox is still checked, indicating that it is still enabled.

I currently have phh's SuperUser disabled. I don't know if it is related, and it seems that I cannot control module enable/disable while Magisk Hide is enabled so I cannot enable phh's SuperUser and try to disable Magisk Hide.

**Comment by bziemek** [comment]
After disabling phh's SuperUser and rebooting, your system has no running su daemon. As a result, Magisk Manager cannot get the necessary permissions to disable hiding, enable modules, or to do much of anything at all.

Make an obligatory backup (at least the boot partition), put your desired Magisk-compatible version of phh's SuperUser on your SD card, and flash it.

**Comment by fsworld009** [comment]
Thanks for explaining, I should not have disabled SuperUser in the first place.

As a note I fixed it by uninstall Magisk and install Magisk v8 (and all modules) again through recovery.

**Comment by bziemek** [comment]
I'm sure plenty of folks have done the same - I know I have!

As a side-note for anyone else who happens across this issue: you can easily obtain a flashable SuperUser zip by hitting the download button in Magisk Manager. Installation will fail, and the downloaded zip will be moved to your SD card so you can flash it manually. This works even if the SuperUser module is already installed but not enabled.

@fsworld009: you should be able to go ahead and close this issue now. :wink:
