### ISSUE TITLE
Amazing bug fix on version 5.1.0

### ISSUE THREAD

**Issue by wuchjun** [topjohnwu/MagiskManager#231]
Many users face the bug on version 5.1.0. App will stuck when opening when you install some modules. It looks like the module.prop file of thoes modules missing a blank line at last cause the bug.Since I add a blank line in module.prop of every module the bug disappeared...

**Comment by RealSpArTeN** [comment]
Can confirm that this works; the Universal Deep_Buffer Remover module didn't have the blank line at the end, added it and Magisk Manager starts up just fine.

#225 Temp fix is to add in an empty line at end of module.prop in /magisk/(module name)/module.prop

**Comment by FabianMeul** [comment]
Confirmed working for Unified Hosts Adblock module as well.

**Comment by JERW86** [comment]
Thank you this worked for me too. 

Phone: XT1625 (Moto G 2016 U.S. Non-Amazon)/ROM: GZR Tesla-athene-7.1.2. OFFICIAL-20170611/Android Version: 7.1.2/Security Patch Level: June 05, 2017/Kernel: ElementalX-G4-1.08-LOS/Magisk v13.3 with Magisk Manager 5.1.0/MagiskSU/microG GmsCore v0.2.4-103/NanoMod Patcher 9.2-20170610/Google Play Store/Recovery: Unofficial TWRP athene 3.1.1_shreps
