### ISSUE TITLE
Magisk Manager - latest update was only 13.1 when latest is 13.3

### ISSUE THREAD

**Issue by Sopor-** [topjohnwu/MagiskManager#232]
When i pressed `Download & Install` in Magisk Manager 4.3.3 it was only showing that the latest Magisk was version 13.1. I then manually update Magisk Manager to 5.0.6 and i did a new `Download & Install` it was now showing 13.3 but Magisk Manager was still 5.0.6 after the update. If i get this right the Manager should also update to latest version that should be 5.1.0?

**Comment by Sopor-** [comment]
Maybe i already found the reason to this? Magisk Manager 4.3.3 is only compatible with Magisk 13.1 Magisk 13.2 and higher needs 5.x.x?

**Comment by dark-basic** [comment]
Not Magisk 13.0 -13.1 - 13.2 and 13.3  is only compatible with Magisk Manager 5.x.x or Higher
Download Magisk Manager  5.1.1
https://github.com/topjohnwu/MagiskManager/releases/download/v5.1.1/MagiskManager-v5.1.1.apk

**Comment by Sopor-** [comment]
Why did Magisk Manager 4.3.3 then wanted to update to 13.1 from 12.0? Then it should update to 13.3 that was released when i did the update check. Yeah, but if it should be like this i will close this issue.

**Comment by dark-basic** [comment]
Because 4.3.3 if you detect that update. The rest no longer
