### ISSUE TITLE
Moto G5 Will not flash v13.3

### ISSUE THREAD

**Issue by Theitfixer85** [topjohnwu/MagiskManager#257]
The moto g5 will not flash v13.3 however it will flash version 11.6 and then you can upgrade to version 13.3 via the magisk manager app however on both versions the policy check fails

here is the boot.img
[boot.zip](https://github.com/topjohnwu/MagiskManager/files/1204880/boot.zip)

You can reach me on xda thefixitman

**Comment by topjohnwu** [comment]
This is not a Magisk Manager bug
