### ISSUE TITLE
Systemless hosts check state can't be changed

### ISSUE THREAD

**Issue by wuchjun** [topjohnwu/MagiskManager#267]
magisk 13.3
magiskmanager 5.1.1

Systemless hosts state has been changed(also see  in the shared_prefs), but the APP  Systemless hosts check can't be changed. Every time i go in the app setting it shows a unchecked state.

**Comment by wuchjun** [comment]
Have been fixed on beta.

**Comment by guest4711** [comment]
Not really. Problem persists on 5.2.0 (170830).

**Comment by guest4711** [comment]
Seems to work now using 5.3.0 on my S4, but non on my maguro.
