### ISSUE TITLE
I can't delete "Busybox for Android NDK" module

### ISSUE THREAD

**Issue by redking974** [topjohnwu/MagiskManager#268]
Hi,
I think I made a mistake because I tried to install Busybox into MagiskManager. I saw after that it must be installed via recovery (on the xda thread about Magisk modules).
So I tried to delete it but when I click on the trash, MM doesn't planify the update/remove of the module.
I tried to install it via the recovery (TWRP) but the error message saying that the module will be update on the next reboot persist. I don't know how to remove these module via MM (or by another way).

Regards.
![screenshot_2017-08-17-23-01-26](https://user-images.githubusercontent.com/23528297/29419253-af70f576-837f-11e7-981f-e49af82f2ce6.png)

**Comment by dark-basic** [comment]
A question. What version of magisk do you have installed ???

**Comment by redking974** [comment]
Hi, the version of Magisk is the lastest stable (13.3) and MM's version is 5.1.1

Regards

**Comment by DeicPro** [comment]
Use a root file explorer and go to root and then magisk folder, there remove busybox-ndk folder

**Comment by redking974** [comment]
Hi, I tried it and it deleted the entry into Magisk Manager. So I close the issue. Thanks !
