### ISSUE TITLE
Magisk manager stopped working and modules failed.

### ISSUE THREAD

**Issue by Explorare** [topjohnwu/MagiskManager#287]
I installed "Unified Hosts Adblock" without error and enabled the "Systemless hosts support" function. But It seems that thiis module doesn't work at all. I tried to visit some ad-block test sites using build in browser and firefox and none of the ads were removed. And every time after the device boot, I got a error message which said "Magisk Manager stopped working". But the built-in SuperSU function works well without error or crash.

**Comment by topjohnwu** [comment]
Module bugs does not belong here
