### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by dna1982** [topjohnwu/MagiskManager#292]
Device: Redmi Note 3 (Kenzo)
Rom: RR-N-v5.8.4-20170827-kenzo-Official
Magisk Ver: 14.0
Magisk Manager Ver: 5.3.0

Logcat :
09-07 15:29:42.027 18404-20139/? E/Magisk: MANAGERERROR: ProcessRepoZip: Error!
09-07 15:29:42.027 18404-20139/? W/System.err: java.io.FileNotFoundException: /storage/emulated/0/MagiskManager/Xposed_Framework_SDK_25-87.2_Systemless_by_topjohnwu.zip (No such file or directory)
09-07 15:29:42.027 18404-20139/? W/System.err:     at java.io.FileOutputStream.open(Native Method)
09-07 15:29:42.027 18404-20139/? W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
09-07 15:29:42.027 18404-20139/? W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:108)
09-07 15:29:42.027 18404-20139/? W/System.err:     at com.topjohnwu.magisk.a.l.b(Unknown Source)
09-07 15:29:42.027 18404-20139/? W/System.err:     at com.topjohnwu.magisk.a.l.doInBackground(Unknown Source)
09-07 15:29:42.027 18404-20139/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:306)
09-07 15:29:42.027 18404-20139/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-07 15:29:42.027 18404-20139/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-07 15:29:42.027 18404-20139/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-07 15:29:42.027 18404-20139/? W/System.err:     at java.lang.Thread.run(Thread.java:761)

I did check the path "/storage/emulated/0/", there is not even a MagiskManager dir.
It seems the zip downloaded did not successfully copied from cache dir to sdcard.

**Comment by dna1982** [comment]
I looked into com.topjohnwu.magisk.asyncs.ProcessRepoZip,java.
I think somehow FileOutputStream does not create mFile, instead throw a FileNotFoundException.
So we'd better create the file by calling mFile.createNewFile() before open a FileOutputStream.

**Comment by topjohnwu** [comment]
Fixed
