### ISSUE TITLE
Magisk Manager 5.3 have problem with downloading modules (MagiskSU 13.7-14.0)

### ISSUE THREAD

**Issue by Blazko381** [topjohnwu/MagiskManager#298]
Magisk Manager 5.3 have problem with downloading modules (Magisk 13.7-14.0). 

To 13.6 version MagiskSU and 5.2 Magisk Manager download module file via Android download manager 13.7 version to 14.0 Magisk Manager 5.3 download module file via Magisk manager, but not download complete. Magisk manager show processing>error process
13.6 version with default 5.2 magisk manager download properly all modules

**Comment by xbach** [comment]
Manually create folder "MagiskManager" in the root of /sdcard

https://github.com/topjohnwu/MagiskManager/issues/299#issuecomment-328916851

**Comment by topjohnwu** [comment]
Fixed
