### ISSUE TITLE
Process Error when installing modules.

### ISSUE THREAD

**Issue by Inforcer25** [topjohnwu/MagiskManager#299]
I reinstalled my ROM Resurrection Remix on the galaxy s4 GT-i9500 and after doing that magisk wont install any modules. I installed magisk by flashing the 14.0 zip file with TWRP (Latest)

Safetynet and everything else is green and working, SuperUser is working too.

Magisk Log:
`--------- beginning of main
I( 2391: 2391) Magisk v14.0(1400) daemon started
I( 2391: 2395) ** post-fs mode running
--------- beginning of system
I( 2391: 2501) ** post-fs-data mode running
I( 2391: 2501) * Mounting mirrors
I( 2391: 2501) mount: /dev/block/platform/dw_mmc.0/by-name/SYSTEM -> /dev/magisk/mirror/system
I( 2391: 2501) link: /dev/magisk/mirror/system/vendor -> /dev/magisk/mirror/vendor
I( 2391: 2501) bind_mount: /dev/magisk/mirror/bin
I( 2391: 2501) Create /data/magisk.img with size 64M
I( 2391: 2501) * Mounting /data/magisk.img
I( 2391: 2501) * Running post-fs-data.d scripts
I( 2391: 2501) * Running module post-fs-data scripts
I( 2391: 2501) * Loading modules
I( 2391: 2510) * Starting MagiskHide
I( 2391: 2510) hide_utils: Hiding sensitive props
E( 2391: 2510) fopen: /magisk/.core/hidelist failed with 2: No such file or directory
I( 2391: 2510) hide_list add: [com.google.android.gms.unstable]
I( 2391: 2510) proc_monitor: init ns=mnt:[4026531840]
I( 2391: 2569) ** late_start service mode running
I( 2391: 2569) * Running service.d scripts
I( 2391: 2569) * Running module service scripts
I( 2391: 2510) proc_monitor: zygote ns=mnt:[4026535501]
I( 2391: 2510) proc_monitor: com.google.android.gms.unstable (PID=4378 ns=mnt:[4026535559])
I( 4388: 4388) hide_daemon: Permissive detected, hide the state
I( 4388: 4388) hide_utils: Re-linking /sbin
E( 5045: 5084) MANAGERERROR: ProcessRepoZip: Error!`

**Comment by xbach** [comment]
Can confirm, same issue.

Workaround: Manually create "MagiskManager" folder in the root of your sdcard. The process fails because the Manager cannot save the downloaded file into the folder, which is not created if you installed MagiskManager by flashing.
