### ISSUE TITLE
App crashes in Magisk Hide section

### ISSUE THREAD

**Issue by DeicPro** [topjohnwu/MagiskManager#41]
When update 5 times (1 initial + 4 manual) Magisk Hide section, the app crashes & in the 4 update some apps disappears.
![screenshot_2017-01-02-21-24-41-894_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12710770/21595787/03af28b6-d132-11e6-9c74-48eaa104e4d3.png)

some apps missing in 4 update:
![screenshot_2017-01-02-21-21-51-435_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12710770/21595793/173c2208-d132-11e6-8146-f7e96c17a8f4.png)

PD: ignore time of screenshots.

**Comment by DeicPro** [comment]
3.1 and no fixed too.

**Comment by aviraxp** [comment]
Strange, try clear data. If still crashes, push a log please.

**Comment by DeicPro** [comment]
@aviraxp clear data did not work.

log:
https://gist.github.com/DeicPro/23d5316eb87d1b0c73a34a823d06b5ec

**Comment by DeicPro** [comment]
Do @topjohnwu can reopen this issue?
