### ISSUE TITLE
Magisk Hide doesn't stick when SuperSu is used

### ISSUE THREAD

**Issue by Shadowghost** [topjohnwu/MagiskManager#42]
When using latest SuperSu 2.79SR1 as su binary you can enable MagiskHide in options but when you do the required reboot it's again disabled.
No idea if it's intentional because of using SuoerSu or not. If latter, it should be fixed if first, the option should just not be available when SuperSu is detected.

**Comment by aviraxp** [comment]
I am aware of this issue too. I noticed in SuperSU log, when magisk tried to run /magisk/.core/magiskhide/add, sush gave permission denied. And some other options are not available too. I guess it is because of the sepolicy issues, as SuperSU changed them a lot since 2.79SR1.

**Comment by JERW86** [comment]
This is not an issue to be fixed. It has been mentioned in the Magisk forum, in general support and other places, that MagiskHide and Chainfire's SuperSu do not work together. You can either: 

1.  use MagiskHide and Magisk compatible Phh Superuser .

2. Use SuperSu and flash Chainfire's suhide and totally ignore/disable MagiskHide all together.

**Comment by Shadowghost** [comment]
I think it is not mentioned in the main thread and I just reported what I experienced. As I already said in my first post: when it is not supported then MagiskHide should just be greyed out.

**Comment by aviraxp** [comment]
Ah, I see https://github.com/topjohnwu/Magisk/commit/e33f5996f3a43e190df7eeb7566d067fcde12b8f, I agree with you.

**Comment by Shadowghost** [comment]
Nice to see, now we can close this ;)
