### ISSUE TITLE
Add app to Fdroid

### ISSUE THREAD

**Issue by captainhook** [topjohnwu/MagiskManager#43]
Some users will not be users Google Play, hence it would be a good idea to also maintain updates through Fdroid.

**Comment by topjohnwu** [comment]
I will always upload a new release APK here on Github and link it in my main thread, so I think it shall handle all the locations with no Play Support.

**Comment by jcgruenhage** [comment]
Although it is possible that users go here every time they want to/need to update the app, updating apps through an app store that automatically checks for an update seems better.

**Comment by jcgruenhage** [comment]
Not that I have time to do that right now, but if someone would do the submission and take care of everything related to F-Droid, would you still be opposed to the inclusion in the F-Droid repositories?

**Comment by nvllsvm** [comment]
I'm looking into this.

**Comment by jcgruenhage** [comment]
There is an F-Droid Policy, that they won't include software when the maintainer is opposed to that. Since that seems to be the case here, you won't have much luck with that I fear.

**Comment by nvllsvm** [comment]
@topjohnwu - Are you opposed to having this in F-Droid if I or someone else takes care of submitting it?

**Comment by nvllsvm** [comment]
@topjohnwu - Are you opposed to having this in F-Droid if I or someone else takes care of submitting it?

@jcgruenhage - Good to know. If @topjohnwu clarifies his opposition to having this in F-Droid, I'll simply fork it and add it myself.

**Comment by thermatk** [comment]
Now that Play is gone, F-Droid is a must
Two things to do in a flavor to satisfy inclusion requirements:
- [ ] prebuilt binaries should be built on compile time
- [ ] google play safety net lib has to go, with the associated functionality. It's sad and checking the safetynet-dependent app itself is less convenient, but this is just a check :+1:

**Comment by nvllsvm** [comment]
@thermatk - the license also needs to be clarified. https://github.com/topjohnwu/MagiskManager/issues/172

**Comment by thermatk** [comment]
#177

**Comment by IzzySoft** [comment]
Meanwhile you can find it [here](https://apt.izzysoft.de/fdroid/index/apk/com.topjohnwu.magisk) to use with the F-Droid client (just add my repo to it). One thing I wonder is: what dependency is there on "Google Mobile Services"? For now, I've marked it `NonFreeDep` because of that, as it usually indicates an app does not run without GApps on the device (though most of it can be covered by microG). I always feel at least a little "insecure" if I see an app depending on such proprietary things, especially "things Google".

**Comment by jcgruenhage** [comment]
It only requires Play Services for the SafetyNet Check, afaik

**Comment by IzzySoft** [comment]
Thanks, @jcgruenhage – I thought so, but wanted to make sure. Apart from `/com/google/android/gms/safetynet` it also addresses `signin`, `auth` and `common`, but that might very well be related. What I'm not sure of: would it fail if PlayServices where not present on the device? If so, probably only the SafetyNet Check then.
