### ISSUE TITLE
Feature request: only show Safety Net status if Magisk Hide enabled.

### ISSUE THREAD

**Issue by Didgeridoohan** [topjohnwu/MagiskManager#47]
A lot of users that have no idea what Safety Net is and have no idea if they need it or not are freaking out because something is showing red in the Magisk Manager.

My suggestion is to only show the Safety Net status if Magisk Hide has been enabled.

**Comment by mamama07-94** [comment]
Well... If you're enabled a hide options it's always is GREEn. Second - 90% of users install magisk just for pass safety net so... ;)

**Comment by topjohnwu** [comment]
Done, 442fcf921c11ebba4eae268cc026a902fdd20383
