### ISSUE TITLE
accessToken for Magisk-Modules-Repo/repos invalid

### ISSUE THREAD

**Issue by marq24** [topjohnwu/MagiskManager#52]
strings.xml

the added access-token 

access_token=8f3c379fbeb80754b45b02486482584893af142a

seams to be not working any longer ?!

I just have fired up my android studio and tested a private build from the master branch where I just already the string.xml file [just removed the acces_token param from the URL]

<stringurl_main name="" translatable="false">https://api.github.com/orgs/Magisk-Modules-Repo/repos</stringurl_main>

and after the apk was deployed I was able to read content again (the jsonString that was requested in the ModuleHelper.createRepoMap(Context context) contained some data)

I would love to make a PR - but I failed so far *shame*

**Comment by tonymanou** [comment]
If you remove the token from the URL, the Github API seems to return something... 😖 
Is the ```access_token``` really necessary?

**Comment by topjohnwu** [comment]
I'm implementing something new now :)
Using conditional requests

**Comment by marq24** [comment]
Good Morning Gentlemen :-)

just as clarification - I initially used incognito mode of chrome in order to test, if the request without access_token would work... and it did - so I modified the code in my local clone of the code.

Also I would just like to repeat, that the current version available via PlayStore have a similar issue - even if the code (url_main) might be different - on a fresh/clean system without any previous versions of MagiskManager installed (empty DB) you will not able to get any modules since the Download fragment will be never populated with data (that was my initial problem yesterday)...

So you might like to consider to deploy a "hotfix" version on PlayStore so that new users will not be pissed off instantly.

**Comment by topjohnwu** [comment]
Fixed here 61e2c3444a68eeda7a56e7eb992c7fa1beac16d7
