### ISSUE TITLE
MagiskHide not working

### ISSUE THREAD

**Issue by stonerl** [topjohnwu/MagiskManager#54]
I'm using Magisk v10.2 and Magisk Manager 3.1 with SuperSU 2.79.  Currently MagiskHide is not working for me. I enable it in the settings and reboot, but after the reboot it is disabled.

**Comment by aviraxp** [comment]
MagiskHide officially no longer works with SuperSU.

**Comment by Shadowghost** [comment]
Correction: it never worked with SuperSu. It was never intended/build to work with it though. There is a red info line in magisk v8 changelog which explicitly states that MagiskHide is not compatible with SuperSu.

**Comment by topjohnwu** [comment]
Just as they said

**Comment by stonerl** [comment]
Hmm, interesting. It was working with SuperSU until I upgraded MagiskManager today.
