### ISSUE TITLE
Magisk v6 bug

### ISSUE THREAD

**Issue by igoticecream** [topjohnwu/MagiskManager#6]
Hello. My ROM comes with a LZ4 compressed boot.img.

The magisk installer fails (silently!!!!, i think you should return 1 immediatly) on this line:

```
$BINDIR/bootimg-extract $ORIGBOOT
```

The script continues and repack an empty folder and flash it.

I repacked my boot.img with gzip compression and the installer do it's job... i think this should be addressed since many people wont know the root of this error and how to fix it.

**Comment by topjohnwu** [comment]
Thanks for the report!
