### ISSUE TITLE
Add some info to SuperSU and SafetyNet

### ISSUE THREAD

**Issue by c727** [topjohnwu/MagiskManager#63]
If SuperSu (or older CM-SUs) is detected you should add some info that Magisk Manager's functionality is limited (eg Magisk Hide not working). Because many users see this green check and think all is fine

Many users spam xda cause they don't pass SafetyNet and don't know why. Maybe you can create a wiki page here in your git (or at xda) and link to it.
Explain:
-what is SafetyNet
-what does it mean when it fails
-why does it fail and how to fix it maybe

**Comment by c727** [comment]
...also add an info that you don't have to check SafetyNet app's (Android Pay) in Magisk Hide cause the associated service is pre-selected in Magisk Hide.
Maybe this can be done by adding pseudo "SafetyNet" at top of the app list and check and disable it

**Comment by topjohnwu** [comment]
Thanks for the suggestions, I definitely need to make it more clearly :)
