### ISSUE TITLE
[Feature] survive ota

### ISSUE THREAD

**Issue by c727** [topjohnwu/MagiskManager#72]
custom roms can use magisk to pass safetynet.

3 possible options for this:
1) for custom roms with addon.d something like this could be added to magisk-manager settings to reflash magisk after rom got flashed https://github.com/osm0sis/GN-Synapse-Injector/blob/master/ramdisk/res/synapse/scripts/999-customkernel.sh

2) detect if new ota was downloaded and provide the user an open recovery script to install update and magisk: http://wiki.rootzwiki.com/OpenRecoveryScript
maybe you can get ota paths from chainfire, sample for lineage:
 /data/data/org.lineageos.updater/app_updates/

3) tell user to use flashfire

for 1) and 2) maybe offer the option to backup kernel (for users with custom kernels)

**Comment by stangri** [comment]
A small comment to the above: last I checked, Flashfire didn't play well with non SuperSu root. IMHO Flashify is a more universal 3rd party alternative.

**Comment by c727** [comment]
@stangri 
Chainfire mentioned at google+ that newest flashfire got support for magisk with phh-topjohnwu-su.
afaik in flashify you can't

**Comment by topjohnwu** [comment]
These problem do not belong to Magisk Manager, please report in XDA thread or Magisk repo

**Comment by salevdns** [comment]
topjohnwu/Magisk#175
