### ISSUE TITLE
[Feature] Stable (Magisk-Modules-Repo) and Beta (developer repo) sources for modules

### ISSUE THREAD

**Issue by stangri** [topjohnwu/MagiskManager#78]
Right now the Magisk Manager checks only https://github.com/Magisk-Modules-Repo for the updates or offers it as the only source for installing the module.

Would be great if at least for installed modules (better yet, all modules in the Magisk-Modules-Repo) there were two sources: Stable (Magisk-Modules-Repo) and Beta/Development (developer repo, from where you forked code to Magisk-Modules-Repo).

That way it would be easier for developers to push new code to their own repo for select users to test, before pushing that code to the official Magisk-Modules-Repo.

Current alternative of posting pre-release ZIP files is cumbersome.

**Comment by stangri** [comment]
Similar to #120.

**Comment by topjohnwu** [comment]
Done

**Comment by topjohnwu** [comment]
Too complicated for me :)
Maybe I'll consider this in the future
