### ISSUE TITLE
[cosmetic] dot/ comma in version number

### ISSUE THREAD

**Issue by c727** [topjohnwu/MagiskManager#86]
using German system language version string shows `v11,0` instead of `v11.0` for example

// see here: https://github.com/topjohnwu/MagiskManager/pull/88#issuecomment-277766377

**Comment by Exalm** [comment]
Same on russian.

**Comment by topjohnwu** [comment]
I think maybe that is the default way the system prints out double values in a German locale
I'll see if I can do anything

**Comment by DeicPro** [comment]
Same on Spanish.

**Comment by c727** [comment]
@topjohnwu yes, we use comma in floating-point numbers here.

My device only supports flashing kernel in fastboot. could you please patch my kernel for magisk or tell me how to do it? thanks https://drive.google.com/file/d/0ByaCo2Stidisc0RlbDROQ0dnVXc/view?usp=sharing

**Comment by topjohnwu** [comment]
I think this was fixed (also not using the same versioning system as before)
