### ISSUE TITLE
[feature] add more details to log for troubleshooting

### ISSUE THREAD

**Issue by c727** [topjohnwu/MagiskManager#91]
-Vendor, Device
-Android version
-SU binary
-Magisk Version
-Magisk Manager version
-Magisk Hide enabled
-Busybox enabled
-script execution timeout
-SE Linux
-USB Debugging
-verified boot
-Xposed installed
-SafetyNet
-PlayStore device certification
"if bootloader unlocked, then it will show up as uncertified.

if the build fingerprint ($adb shell getprop | grep finger) is not certified by the OEM, then it will show up as uncertified

if the build spoofs another legit device, then its likely going to appear as uncertified."

**Comment by Didgeridoohan** [comment]
I second this. Would be very useful when troubleshooting.

**Comment by topjohnwu** [comment]
Logs are now different than usual, also this problem do not belong to Magisk Manager
