### ISSUE TITLE
Settings' sliders don't slide when you slide them

### ISSUE THREAD

**Issue by DeicPro** [topjohnwu/MagiskManager#93]
![img_20170210_211859](https://cloud.githubusercontent.com/assets/12710770/22842867/25f4ea64-efd7-11e6-839a-89ae0aa6f794.jpg)

**Comment by topjohnwu** [comment]
It is caused by the activity re-creating (for themes to apply), there is no bug here.

**Comment by DeicPro** [comment]
And that affects to all sliders? Wow...
